### ISSUE TITLE
is this actually works?

### ISSUE THREAD

**Issue by hasunpark** [justadudewhohacks/opencv-electron#20]
I just clone plain-js and when 'npm install' error happens at node-gyp rebuild. 
I try and search about every docs but there is no way to run it

**Comment by adgarcis** [comment]
The same problem.
Not run

**Comment by hasunpark** [comment]
https://github.com/justadudewhohacks/opencv4nodejs/issues/642
try this solution

**Comment by adgarcis** [comment]
Thanks!! It's working
