### ISSUE TITLE
electron.desktopCapturer to cv.VideoCapture

### ISSUE THREAD

**Issue by developer239** [justadudewhohacks/opencv-electron#6]
Hi, :)
awesome library as always. I spent couple hours browsing the internet and searching for some solution how to capture desktop (or window) and send it to OpenCv. I got it working on Linux but I was unable to make it work on Mac. Then I found Electron and its `desktopCapturer`. So I started using Electron...

**I would like to be able to send the recorded screen to your OpenCV library.**

a) Simply starting stream using `desktopCapturer` and passing the stream to your opencv library.

I have this code:

```
navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: source.id,
      minWidth: 640,
      maxWidth: 640,
      minHeight: 320,
      maxHeight: 320,
    },
  },
})
.then((stream) => {
  console.log('stream ', stream);
  const videoUrl = URL.createObjectURL(stream);
  console.log('videoUrl', videoUrl);
  const capturedVideo = new cv.VideoCapture(videoUrl);
  console.log('captured video', capturedVideo);
})
.catch((error) => console.error(error));
```

But I get following error:
![image](https://user-images.githubusercontent.com/14946081/34911833-43e6256a-f8d2-11e7-8078-1fe5f66d56e1.png)

b) Stream the `MediaStream` object to Nodejs server and process the `MediaStream` using your OpenCV library.

Is a) or b) possible? :)

Thank you

**Comment by justadudewhohacks** [comment]
Hmm I am not sure if the OpenCV VideoCapture accepts this kind of file as input.

Anyways, you should be able to extract OpenCV Mat's from any kinds of image streams by using the constructor, which takes the raw data as input `new cv.Mat(buf, rows, cols, type)`. You just have to pipe your stream into a node buffer. Atleast that's how it works with streaming images with socket.io.

**Comment by developer239** [comment]
That makes sense. This is probably not a best way of taking an image but after a while I managed to get still image and convert it to node buffer like this:

```
navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: source.id,
      minWidth: 1000,
      maxWidth: 1000,
      minHeight: 1000,
      maxHeight: 1000,
    },
  },
})
.then((stream) => {
  const track = stream.getVideoTracks()[0];
  const capturedImage = new ImageCapture(track);

  capturedImage
    .takePhoto()
    .then(blob => {
      toBuffer(blob, function (err, buffer) { // TODO: This is probably not necessary?
        if (err) throw err;
        const appDownloadsPath = electron.remote.app.getPath('downloads');
        fs.writeFileSync(`${appDownloadsPath}/image.png`, buffer); // This works fine I can see the image in good quality

        const matFromArray = new cv.Mat(buffer, 1000, 1000, cv.CV_8UC3);
        cv.imshowWait('mat array', matFromArray);
      });
    })
    .catch(error => console.error('takePhoto() error:', error));
```

I am probably missing some settings here `const matFromArray = new cv.Mat(buffer, 1000, 1000, cv.CV_8UC3);` Beceause when I save the image it looks fine. However when I `imshowWait` the image it looks like this:

![image](https://user-images.githubusercontent.com/14946081/34916848-b7411792-f93e-11e7-9377-5a0a07632c01.png)

**Comment by justadudewhohacks** [comment]
Can you check `console.log(buffer.length)`. The length of the buffer should equals `rows * cols * channels` in your case `1000 * 1000 * 3`.

**Comment by developer239** [comment]
Hmm :D

![image](https://user-images.githubusercontent.com/14946081/34918169-b497dee4-f94e-11e7-9bbe-712c112b2c78.png)

Do you know how to fix that? I have Macbook retina screen. Resolution is `1440x900`

When I change size like this:

```
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: source.id,
      minWidth: 1440,
      maxWidth: 1440,
      minHeight: 900,
      maxHeight: 900,
    },
```

Then I get this buffer:
![image](https://user-images.githubusercontent.com/14946081/34918190-1d014cb8-f94f-11e7-8fd4-fb486c7ea2ad.png)

**Comment by justadudewhohacks** [comment]
Okay I guess the data of your image is compressed, since the raw data size does not match. Can you set codec options to figure out how to decode the data?

You could try to `const mat = cv.imdecode(buffer)` in case this is a valid codec, which is known to opencv.

Or in case it's not base64 encoded: 
```
const base64Buf = Buffer.from(buffer.data, 'base64')
cv.imdecode(base64Buf)
```

**Comment by developer239** [comment]
That is awesome. I believe it works now. Thanks a lot. :)

**Comment by justadudewhohacks** [comment]
Great, which one was the solution?

**Comment by developer239** [comment]
I just used `cv.imdecode(base64Buf)` it returned the matrix succesffully.

```
  capturedImage
    .takePhoto()
    .then(blob => {
      toBuffer(blob, function (err, buffer) { // TODO: This is probably not necessary?
        if (err) throw err;
        const appDownloadsPath = electron.remote.app.getPath('downloads');
        fs.writeFileSync(`${appDownloadsPath}/image.png`, buffer); // This works fine I can see the image in good quality

        const mat = cv.imdecode(buffer);
        cv.imshowWait('ma', mat);
      });
    })
    .catch(error => console.error('takePhoto() error:', error));
```
