### ISSUE TITLE
Converting matrix to base64 string

### ISSUE THREAD

**Issue by developer239** [justadudewhohacks/opencv-electron#7]
Hey,
I have problems converting `Mat` to a `base64 string`.

I have this stream function that basically creates `opencv mat` and sends it to another window:

```
export const stream = (video, canvas) => {
  // Draw video frame to canvas
  canvas.getContext('2d').drawImage(video, 0, 0, GAME_WINDOW_WIDTH, GAME_WINDOW_HEIGHT)
  // Convert canvas to blob
  canvas.toBlob((blob) => {
    // Convert canvas to buffer
    toBuffer(blob, (err, buffer) => {
      // Convert buffer to opencv mat
      const mat = cv.imdecode(buffer)
      mat.getDataAsync((error, buffer) => {
        if (error) {
          throw error
        }
        // Send buffer to another window
        send(SEND_VIDEO_SCREEN, buffer)
      })
      setTimeout(() => {
        stream(video, canvas)
      }, 1000 / FPS)
    })
  })
}
```
In another window I have this code (for simplicty I decided to pass the `base64 string` directly to image source)

```
listenTo(SEND_VIDEO_SCREEN, (event, args) => {
  this.setState({ imageSrc: args.payload.toString('base64') })
})
```
Now the problem is that I can't display the image.

**1) The code above crashes the second renderer window.**

**2) Converting to base64string in the first window was slow and it also did not work:** ```
```
send(SEND_VIDEO_SCREEN, buffer.toString('base64'))
```

**3) Then I tried sending unit8array to renderer:**

```
send(SEND_VIDEO_SCREEN, new Uint8Array(buffer))
```

```
listenTo(SEND_VIDEO_SCREEN, (event, args) => {
  const base64String = Uint8ToBase64(args.payload)
  image.src = `data:image/png;base64,${base64String}`
})
```

It looks like there is something weird going on in the background? Maybe I have wrong `data:image/png;base64`? (I tried basically all image types) Have you encountered a similar problem before? Could you help me out please? :)

**Comment by justadudewhohacks** [comment]
Well the correct way to initialize a mat from base64 would be somehow like this:

```
// load base64 encoded image
const base64text='data:image/png;base64,R0lGO..';//Base64 encoded string
const base64data =base64text.replace('data:image/jpeg;base64','')
                            .replace('data:image/png;base64','');//Strip image type prefix
const buffer = Buffer.from(base64data,'base64');
const image = cv.imdecode(buffer); //Image is now represented as Mat

// convert Mat to base64 encoded jpg image
const outBase64 =  cv.imencode('.jpg', croppedImage).toString('base64'); // Perform base64 encoding
const htmlImg='<img src=data:image/jpeg;base64,'+outBase64 + '>'; //Create insert into HTML compatible <img> tag
```

I haven't encountered problems before. May also the opencv-express [example](https://github.com/justadudewhohacks/opencv-express/blob/master/src/services/imgcodecs.js) helps you.

What specifically does not work about it, does it simply crash? If so, is there any stacktrace or error output?

**Comment by developer239** [comment]
@justadudewhohacks Awesome as always thank you :)

![image](https://user-images.githubusercontent.com/14946081/35292418-b442776e-0070-11e8-83ca-b84557203f2b.png)

**Comment by justadudewhohacks** [comment]
What kind of app are you building. :D

**Comment by developer239** [comment]
@justadudewhohacks Bot for swords and souls game 😄 But I am trying to make it the right way (I was experimenting with haar cascades for a while) so that I can reuse the code in some other projects in the future.

This is what I had like 6 months ago. (it actually plays the game itself)

Now I am trying to make it work in electron and your node opencv library.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14946081/35331470-c82f8b44-0107-11e8-86ed-89f504e2c913.gif)

**Comment by developer239** [comment]
@justadudewhohacks Bot for swords and souls game 😄 But I am trying to make it the right way (I was experimenting with haar cascades for a while) so that I can reuse the code in some other projects in the future.

This is what I had like 6 months ago. (it actually plays the game itself)

Now I am trying to make it work in electron and your node opencv library.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14946081/35331556-1cebf000-0108-11e8-9b84-fbf527bd272a.gif)

**Comment by justadudewhohacks** [comment]
Wow, that looks awesome :D

**Comment by leo-def** [comment]
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
server_1      |     at Function.Buffer.from

**Comment by leo-def** [comment]
Can I use this converted image for training face recognition or FaceLandmark5Predictor or FaceLandmark68Predictor? It's throwing `Error: JitterImage - Error: expected argument 0 to be of type ImageRGB` Can I convert it to ImageRGB ?

**Comment by justadudewhohacks** [comment]
face-recognition.js is a different package, so you can not simply pass in a cv.Mat into the function call. But yes you can convert cv.Mat into ImageRGBs, therefore have a look at the [examples](https://github.com/justadudewhohacks/face-recognition.js/tree/master/examples/opencv4nodejs) for how to use face-recognition.js with opencv4nodejs .

**Comment by VaneeshK** [comment]
Hi ,
My code is based on typescript, is there a way to load base64 image to MAT object, without using Buffer. I tried everything like creating MAT from canvas and base64. Its always failing.
